export const localData = {
  projLicenseText: `
__________________GNU_LESSER_GENERAL_PUBLIC_LICENSE
_______________________Version_2.1,_February_1999

_Copyright_(C)_1991,_1999_Free_Software_Foundation,_Inc.
_51_Franklin_Street,_Fifth_Floor,_Boston,_MA__02110-1301__USA
_Everyone_is_permitted_to_copy_and_distribute_verbatim_copies
_of_this_license_document,_but_changing_it_is_not_allowed.

[This_is_the_first_released_version_of_the_Lesser_GPL.__It_also_counts
_as_the_successor_of_the_GNU_Library_Public_License,_version_2,_hence
_the_version_number_2.1.]

____________________________Preamble

__The_licenses_for_most_software_are_designed_to_take_away_your
freedom_to_share_and_change_it.__By_contrast,_the_GNU_General_Public
Licenses_are_intended_to_guarantee_your_freedom_to_share_and_change
free_software--to_make_sure_the_software_is_free_for_all_its_users.

__This_license,_the_Lesser_General_Public_License,_applies_to_some
specially_designated_software_packages--typically_libraries--of_the
Free_Software_Foundation_and_other_authors_who_decide_to_use_it.__You
can_use_it_too,_but_we_suggest_you_first_think_carefully_about_whether
this_license_or_the_ordinary_General_Public_License_is_the_better
strategy_to_use_in_any_particular_case,_based_on_the_explanations_below.

__When_we_speak_of_free_software,_we_are_referring_to_freedom_of_use,
not_price.__Our_General_Public_Licenses_are_designed_to_make_sure_that
you_have_the_freedom_to_distribute_copies_of_free_software_(and_charge
for_this_service_if_you_wish);_that_you_receive_source_code_or_can_get
it_if_you_want_it;_that_you_can_change_the_software_and_use_pieces_of
it_in_new_free_programs;_and_that_you_are_informed_that_you_can_do
these_things.

__To_protect_your_rights,_we_need_to_make_restrictions_that_forbid
distributors_to_deny_you_these_rights_or_to_ask_you_to_surrender_these
rights.__These_restrictions_translate_to_certain_responsibilities_for
you_if_you_distribute_copies_of_the_library_or_if_you_modify_it.

__For_example,_if_you_distribute_copies_of_the_library,_whether_gratis
or_for_a_fee,_you_must_give_the_recipients_all_the_rights_that_we_gave
you.__You_must_make_sure_that_they,_too,_receive_or_can_get_the_source
code.__If_you_link_other_code_with_the_library,_you_must_provide
complete_object_files_to_the_recipients,_so_that_they_can_relink_them
with_the_library_after_making_changes_to_the_library_and_recompiling
it.__And_you_must_show_them_these_terms_so_they_know_their_rights.

__We_protect_your_rights_with_a_two-step_method:_(1)_we_copyright_the
library,_and_(2)_we_offer_you_this_license,_which_gives_you_legal
permission_to_copy,_distribute_and/or_modify_the_library.

__To_protect_each_distributor,_we_want_to_make_it_very_clear_that
there_is_no_warranty_for_the_free_library.__Also,_if_the_library_is
modified_by_someone_else_and_passed_on,_the_recipients_should_know
that_what_they_have_is_not_the_original_version,_so_that_the_original
author's_reputation_will_not_be_affected_by_problems_that_might_be
introduced_by_others.

__Finally,_software_patents_pose_a_constant_threat_to_the_existence_of
any_free_program.__We_wish_to_make_sure_that_a_company_cannot
effectively_restrict_the_users_of_a_free_program_by_obtaining_a
restrictive_license_from_a_patent_holder.__Therefore,_we_insist_that
any_patent_license_obtained_for_a_version_of_the_library_must_be
consistent_with_the_full_freedom_of_use_specified_in_this_license.

__Most_GNU_software,_including_some_libraries,_is_covered_by_the
ordinary_GNU_General_Public_License.__This_license,_the_GNU_Lesser
General_Public_License,_applies_to_certain_designated_libraries,_and
is_quite_different_from_the_ordinary_General_Public_License.__We_use
this_license_for_certain_libraries_in_order_to_permit_linking_those
libraries_into_non-free_programs.

__When_a_program_is_linked_with_a_library,_whether_statically_or_using
a_shared_library,_the_combination_of_the_two_is_legally_speaking_a
combined_work,_a_derivative_of_the_original_library.__The_ordinary
General_Public_License_therefore_permits_such_linking_only_if_the
entire_combination_fits_its_criteria_of_freedom.__The_Lesser_General
Public_License_permits_more_lax_criteria_for_linking_other_code_with
the_library.

__We_call_this_license_the_"Lesser"_General_Public_License_because_it
does_Less_to_protect_the_user's_freedom_than_the_ordinary_General
Public_License.__It_also_provides_other_free_software_developers_Less
of_an_advantage_over_competing_non-free_programs.__These_disadvantages
are_the_reason_we_use_the_ordinary_General_Public_License_for_many
libraries.__However,_the_Lesser_license_provides_advantages_in_certain
special_circumstances.

__For_example,_on_rare_occasions,_there_may_be_a_special_need_to
encourage_the_widest_possible_use_of_a_certain_library,_so_that_it_becomes
a_de-facto_standard.__To_achieve_this,_non-free_programs_must_be
allowed_to_use_the_library.__A_more_frequent_case_is_that_a_free
library_does_the_same_job_as_widely_used_non-free_libraries.__In_this
case,_there_is_little_to_gain_by_limiting_the_free_library_to_free
software_only,_so_we_use_the_Lesser_General_Public_License.

__In_other_cases,_permission_to_use_a_particular_library_in_non-free
programs_enables_a_greater_number_of_people_to_use_a_large_body_of
free_software.__For_example,_permission_to_use_the_GNU_C_Library_in
non-free_programs_enables_many_more_people_to_use_the_whole_GNU
operating_system,_as_well_as_its_variant,_the_GNU/Linux_operating
system.

__Although_the_Lesser_General_Public_License_is_Less_protective_of_the
users'_freedom,_it_does_ensure_that_the_user_of_a_program_that_is
linked_with_the_Library_has_the_freedom_and_the_wherewithal_to_run
that_program_using_a_modified_version_of_the_Library.

__The_precise_terms_and_conditions_for_copying,_distribution_and
modification_follow.__Pay_close_attention_to_the_difference_between_a
"work_based_on_the_library"_and_a_"work_that_uses_the_library".__The
former_contains_code_derived_from_the_library,_whereas_the_latter_must
be_combined_with_the_library_in_order_to_run.

__________________GNU_LESSER_GENERAL_PUBLIC_LICENSE
___TERMS_AND_CONDITIONS_FOR_COPYING,_DISTRIBUTION_AND_MODIFICATION

__0._This_License_Agreement_applies_to_any_software_library_or_other
program_which_contains_a_notice_placed_by_the_copyright_holder_or
other_authorized_party_saying_it_may_be_distributed_under_the_terms_of
this_Lesser_General_Public_License_(also_called_"this_License").
Each_licensee_is_addressed_as_"you".

__A_"library"_means_a_collection_of_software_functions_and/or_data
prepared_so_as_to_be_conveniently_linked_with_application_programs
(which_use_some_of_those_functions_and_data)_to_form_executables.

__The_"Library",_below,_refers_to_any_such_software_library_or_work
which_has_been_distributed_under_these_terms.__A_"work_based_on_the
Library"_means_either_the_Library_or_any_derivative_work_under
copyright_law:_that_is_to_say,_a_work_containing_the_Library_or_a
portion_of_it,_either_verbatim_or_with_modifications_and/or_translated
straightforwardly_into_another_language.__(Hereinafter,_translation_is
included_without_limitation_in_the_term_"modification".)

__"Source_code"_for_a_work_means_the_preferred_form_of_the_work_for
making_modifications_to_it.__For_a_library,_complete_source_code_means
all_the_source_code_for_all_modules_it_contains,_plus_any_associated
interface_definition_files,_plus_the_scripts_used_to_control_compilation
and_installation_of_the_library.

__Activities_other_than_copying,_distribution_and_modification_are_not
covered_by_this_License;_they_are_outside_its_scope.__The_act_of
running_a_program_using_the_Library_is_not_restricted,_and_output_from
such_a_program_is_covered_only_if_its_contents_constitute_a_work_based
on_the_Library_(independent_of_the_use_of_the_Library_in_a_tool_for
writing_it).__Whether_that_is_true_depends_on_what_the_Library_does
and_what_the_program_that_uses_the_Library_does.

__1._You_may_copy_and_distribute_verbatim_copies_of_the_Library's
complete_source_code_as_you_receive_it,_in_any_medium,_provided_that
you_conspicuously_and_appropriately_publish_on_each_copy_an
appropriate_copyright_notice_and_disclaimer_of_warranty;_keep_intact
all_the_notices_that_refer_to_this_License_and_to_the_absence_of_any
warranty;_and_distribute_a_copy_of_this_License_along_with_the
Library.

__You_may_charge_a_fee_for_the_physical_act_of_transferring_a_copy,
and_you_may_at_your_option_offer_warranty_protection_in_exchange_for_a
fee.

__2._You_may_modify_your_copy_or_copies_of_the_Library_or_any_portion
of_it,_thus_forming_a_work_based_on_the_Library,_and_copy_and
distribute_such_modifications_or_work_under_the_terms_of_Section_1
above,_provided_that_you_also_meet_all_of_these_conditions:

____a)_The_modified_work_must_itself_be_a_software_library.

____b)_You_must_cause_the_files_modified_to_carry_prominent_notices
____stating_that_you_changed_the_files_and_the_date_of_any_change.

____c)_You_must_cause_the_whole_of_the_work_to_be_licensed_at_no
____charge_to_all_third_parties_under_the_terms_of_this_License.

____d)_If_a_facility_in_the_modified_Library_refers_to_a_function_or_a
____table_of_data_to_be_supplied_by_an_application_program_that_uses
____the_facility,_other_than_as_an_argument_passed_when_the_facility
____is_invoked,_then_you_must_make_a_good_faith_effort_to_ensure_that,
____in_the_event_an_application_does_not_supply_such_function_or
____table,_the_facility_still_operates,_and_performs_whatever_part_of
____its_purpose_remains_meaningful.

____(For_example,_a_function_in_a_library_to_compute_square_roots_has
____a_purpose_that_is_entirely_well-defined_independent_of_the
____application.__Therefore,_Subsection_2d_requires_that_any
____application-supplied_function_or_table_used_by_this_function_must
____be_optional:_if_the_application_does_not_supply_it,_the_square
____root_function_must_still_compute_square_roots.)

These_requirements_apply_to_the_modified_work_as_a_whole.__If
identifiable_sections_of_that_work_are_not_derived_from_the_Library,
and_can_be_reasonably_considered_independent_and_separate_works_in
themselves,_then_this_License,_and_its_terms,_do_not_apply_to_those
sections_when_you_distribute_them_as_separate_works.__But_when_you
distribute_the_same_sections_as_part_of_a_whole_which_is_a_work_based
on_the_Library,_the_distribution_of_the_whole_must_be_on_the_terms_of
this_License,_whose_permissions_for_other_licensees_extend_to_the
entire_whole,_and_thus_to_each_and_every_part_regardless_of_who_wrote
it.

Thus,_it_is_not_the_intent_of_this_section_to_claim_rights_or_contest
your_rights_to_work_written_entirely_by_you;_rather,_the_intent_is_to
exercise_the_right_to_control_the_distribution_of_derivative_or
collective_works_based_on_the_Library.

In_addition,_mere_aggregation_of_another_work_not_based_on_the_Library
with_the_Library_(or_with_a_work_based_on_the_Library)_on_a_volume_of
a_storage_or_distribution_medium_does_not_bring_the_other_work_under
the_scope_of_this_License.

__3._You_may_opt_to_apply_the_terms_of_the_ordinary_GNU_General_Public
License_instead_of_this_License_to_a_given_copy_of_the_Library.__To_do
this,_you_must_alter_all_the_notices_that_refer_to_this_License,_so
that_they_refer_to_the_ordinary_GNU_General_Public_License,_version_2,
instead_of_to_this_License.__(If_a_newer_version_than_version_2_of_the
ordinary_GNU_General_Public_License_has_appeared,_then_you_can_specify
that_version_instead_if_you_wish.)__Do_not_make_any_other_change_in
these_notices.

__Once_this_change_is_made_in_a_given_copy,_it_is_irreversible_for
that_copy,_so_the_ordinary_GNU_General_Public_License_applies_to_all
subsequent_copies_and_derivative_works_made_from_that_copy.

__This_option_is_useful_when_you_wish_to_copy_part_of_the_code_of
the_Library_into_a_program_that_is_not_a_library.

__4._You_may_copy_and_distribute_the_Library_(or_a_portion_or
derivative_of_it,_under_Section_2)_in_object_code_or_executable_form
under_the_terms_of_Sections_1_and_2_above_provided_that_you_accompany
it_with_the_complete_corresponding_machine-readable_source_code,_which
must_be_distributed_under_the_terms_of_Sections_1_and_2_above_on_a
medium_customarily_used_for_software_interchange.

__If_distribution_of_object_code_is_made_by_offering_access_to_copy
from_a_designated_place,_then_offering_equivalent_access_to_copy_the
source_code_from_the_same_place_satisfies_the_requirement_to
distribute_the_source_code,_even_though_third_parties_are_not
compelled_to_copy_the_source_along_with_the_object_code.

__5._A_program_that_contains_no_derivative_of_any_portion_of_the
Library,_but_is_designed_to_work_with_the_Library_by_being_compiled_or
linked_with_it,_is_called_a_"work_that_uses_the_Library".__Such_a
work,_in_isolation,_is_not_a_derivative_work_of_the_Library,_and
therefore_falls_outside_the_scope_of_this_License.

__However,_linking_a_"work_that_uses_the_Library"_with_the_Library
creates_an_executable_that_is_a_derivative_of_the_Library_(because_it
contains_portions_of_the_Library),_rather_than_a_"work_that_uses_the
library".__The_executable_is_therefore_covered_by_this_License.
Section_6_states_terms_for_distribution_of_such_executables.

__When_a_"work_that_uses_the_Library"_uses_material_from_a_header_file
that_is_part_of_the_Library,_the_object_code_for_the_work_may_be_a
derivative_work_of_the_Library_even_though_the_source_code_is_not.
Whether_this_is_true_is_especially_significant_if_the_work_can_be
linked_without_the_Library,_or_if_the_work_is_itself_a_library.__The
threshold_for_this_to_be_true_is_not_precisely_defined_by_law.

__If_such_an_object_file_uses_only_numerical_parameters,_data
structure_layouts_and_accessors,_and_small_macros_and_small_inline
functions_(ten_lines_or_less_in_length),_then_the_use_of_the_object
file_is_unrestricted,_regardless_of_whether_it_is_legally_a_derivative
work.__(Executables_containing_this_object_code_plus_portions_of_the
Library_will_still_fall_under_Section_6.)

__Otherwise,_if_the_work_is_a_derivative_of_the_Library,_you_may
distribute_the_object_code_for_the_work_under_the_terms_of_Section_6.
Any_executables_containing_that_work_also_fall_under_Section_6,
whether_or_not_they_are_linked_directly_with_the_Library_itself.

__6._As_an_exception_to_the_Sections_above,_you_may_also_combine_or
link_a_"work_that_uses_the_Library"_with_the_Library_to_produce_a
work_containing_portions_of_the_Library,_and_distribute_that_work
under_terms_of_your_choice,_provided_that_the_terms_permit
modification_of_the_work_for_the_customer's_own_use_and_reverse
engineering_for_debugging_such_modifications.

__You_must_give_prominent_notice_with_each_copy_of_the_work_that_the
Library_is_used_in_it_and_that_the_Library_and_its_use_are_covered_by
this_License.__You_must_supply_a_copy_of_this_License.__If_the_work
during_execution_displays_copyright_notices,_you_must_include_the
copyright_notice_for_the_Library_among_them,_as_well_as_a_reference
directing_the_user_to_the_copy_of_this_License.__Also,_you_must_do_one
of_these_things:

____a)_Accompany_the_work_with_the_complete_corresponding
____machine-readable_source_code_for_the_Library_including_whatever
____changes_were_used_in_the_work_(which_must_be_distributed_under
____Sections_1_and_2_above);_and,_if_the_work_is_an_executable_linked
____with_the_Library,_with_the_complete_machine-readable_"work_that
____uses_the_Library",_as_object_code_and/or_source_code,_so_that_the
____user_can_modify_the_Library_and_then_relink_to_produce_a_modified
____executable_containing_the_modified_Library.__(It_is_understood
____that_the_user_who_changes_the_contents_of_definitions_files_in_the
____Library_will_not_necessarily_be_able_to_recompile_the_application
____to_use_the_modified_definitions.)

____b)_Use_a_suitable_shared_library_mechanism_for_linking_with_the
____Library.__A_suitable_mechanism_is_one_that_(1)_uses_at_run_time_a
____copy_of_the_library_already_present_on_the_user's_computer_system,
____rather_than_copying_library_functions_into_the_executable,_and_(2)
____will_operate_properly_with_a_modified_version_of_the_library,_if
____the_user_installs_one,_as_long_as_the_modified_version_is
____interface-compatible_with_the_version_that_the_work_was_made_with.

____c)_Accompany_the_work_with_a_written_offer,_valid_for_at
____least_three_years,_to_give_the_same_user_the_materials
____specified_in_Subsection_6a,_above,_for_a_charge_no_more
____than_the_cost_of_performing_this_distribution.

____d)_If_distribution_of_the_work_is_made_by_offering_access_to_copy
____from_a_designated_place,_offer_equivalent_access_to_copy_the_above
____specified_materials_from_the_same_place.

____e)_Verify_that_the_user_has_already_received_a_copy_of_these
____materials_or_that_you_have_already_sent_this_user_a_copy.

__For_an_executable,_the_required_form_of_the_"work_that_uses_the
Library"_must_include_any_data_and_utility_programs_needed_for
reproducing_the_executable_from_it.__However,_as_a_special_exception,
the_materials_to_be_distributed_need_not_include_anything_that_is
normally_distributed_(in_either_source_or_binary_form)_with_the_major
components_(compiler,_kernel,_and_so_on)_of_the_operating_system_on
which_the_executable_runs,_unless_that_component_itself_accompanies
the_executable.

__It_may_happen_that_this_requirement_contradicts_the_license
restrictions_of_other_proprietary_libraries_that_do_not_normally
accompany_the_operating_system.__Such_a_contradiction_means_you_cannot
use_both_them_and_the_Library_together_in_an_executable_that_you
distribute.

__7._You_may_place_library_facilities_that_are_a_work_based_on_the
Library_side-by-side_in_a_single_library_together_with_other_library
facilities_not_covered_by_this_License,_and_distribute_such_a_combined
library,_provided_that_the_separate_distribution_of_the_work_based_on
the_Library_and_of_the_other_library_facilities_is_otherwise
permitted,_and_provided_that_you_do_these_two_things:

____a)_Accompany_the_combined_library_with_a_copy_of_the_same_work
____based_on_the_Library,_uncombined_with_any_other_library
____facilities.__This_must_be_distributed_under_the_terms_of_the
____Sections_above.

____b)_Give_prominent_notice_with_the_combined_library_of_the_fact
____that_part_of_it_is_a_work_based_on_the_Library,_and_explaining
____where_to_find_the_accompanying_uncombined_form_of_the_same_work.

__8._You_may_not_copy,_modify,_sublicense,_link_with,_or_distribute
the_Library_except_as_expressly_provided_under_this_License.__Any
attempt_otherwise_to_copy,_modify,_sublicense,_link_with,_or
distribute_the_Library_is_void,_and_will_automatically_terminate_your
rights_under_this_License.__However,_parties_who_have_received_copies,
or_rights,_from_you_under_this_License_will_not_have_their_licenses
terminated_so_long_as_such_parties_remain_in_full_compliance.

__9._You_are_not_required_to_accept_this_License,_since_you_have_not
signed_it.__However,_nothing_else_grants_you_permission_to_modify_or
distribute_the_Library_or_its_derivative_works.__These_actions_are
prohibited_by_law_if_you_do_not_accept_this_License.__Therefore,_by
modifying_or_distributing_the_Library_(or_any_work_based_on_the
Library),_you_indicate_your_acceptance_of_this_License_to_do_so,_and
all_its_terms_and_conditions_for_copying,_distributing_or_modifying
the_Library_or_works_based_on_it.

__10._Each_time_you_redistribute_the_Library_(or_any_work_based_on_the
Library),_the_recipient_automatically_receives_a_license_from_the
original_licensor_to_copy,_distribute,_link_with_or_modify_the_Library
subject_to_these_terms_and_conditions.__You_may_not_impose_any_further
restrictions_on_the_recipients'_exercise_of_the_rights_granted_herein.
You_are_not_responsible_for_enforcing_compliance_by_third_parties_with
this_License.

__11._If,_as_a_consequence_of_a_court_judgment_or_allegation_of_patent
infringement_or_for_any_other_reason_(not_limited_to_patent_issues),
conditions_are_imposed_on_you_(whether_by_court_order,_agreement_or
otherwise)_that_contradict_the_conditions_of_this_License,_they_do_not
excuse_you_from_the_conditions_of_this_License.__If_you_cannot
distribute_so_as_to_satisfy_simultaneously_your_obligations_under_this
License_and_any_other_pertinent_obligations,_then_as_a_consequence_you
may_not_distribute_the_Library_at_all.__For_example,_if_a_patent
license_would_not_permit_royalty-free_redistribution_of_the_Library_by
all_those_who_receive_copies_directly_or_indirectly_through_you,_then
the_only_way_you_could_satisfy_both_it_and_this_License_would_be_to
refrain_entirely_from_distribution_of_the_Library.

If_any_portion_of_this_section_is_held_invalid_or_unenforceable_under_any
particular_circumstance,_the_balance_of_the_section_is_intended_to_apply,
and_the_section_as_a_whole_is_intended_to_apply_in_other_circumstances.

It_is_not_the_purpose_of_this_section_to_induce_you_to_infringe_any
patents_or_other_property_right_claims_or_to_contest_validity_of_any
such_claims;_this_section_has_the_sole_purpose_of_protecting_the
integrity_of_the_free_software_distribution_system_which_is
implemented_by_public_license_practices.__Many_people_have_made
generous_contributions_to_the_wide_range_of_software_distributed
through_that_system_in_reliance_on_consistent_application_of_that
system;_it_is_up_to_the_author/donor_to_decide_if_he_or_she_is_willing
to_distribute_software_through_any_other_system_and_a_licensee_cannot
impose_that_choice.

This_section_is_intended_to_make_thoroughly_clear_what_is_believed_to
be_a_consequence_of_the_rest_of_this_License.

__12._If_the_distribution_and/or_use_of_the_Library_is_restricted_in
certain_countries_either_by_patents_or_by_copyrighted_interfaces,_the
original_copyright_holder_who_places_the_Library_under_this_License_may_add
an_explicit_geographical_distribution_limitation_excluding_those_countries,
so_that_distribution_is_permitted_only_in_or_among_countries_not_thus
excluded.__In_such_case,_this_License_incorporates_the_limitation_as_if
written_in_the_body_of_this_License.

__13._The_Free_Software_Foundation_may_publish_revised_and/or_new
versions_of_the_Lesser_General_Public_License_from_time_to_time.
Such_new_versions_will_be_similar_in_spirit_to_the_present_version,
but_may_differ_in_detail_to_address_new_problems_or_concerns.

Each_version_is_given_a_distinguishing_version_number.__If_the_Library
specifies_a_version_number_of_this_License_which_applies_to_it_and
"any_later_version",_you_have_the_option_of_following_the_terms_and
conditions_either_of_that_version_or_of_any_later_version_published_by
the_Free_Software_Foundation.__If_the_Library_does_not_specify_a
license_version_number,_you_may_choose_any_version_ever_published_by
the_Free_Software_Foundation.

__14._If_you_wish_to_incorporate_parts_of_the_Library_into_other_free
programs_whose_distribution_conditions_are_incompatible_with_these,
write_to_the_author_to_ask_for_permission.__For_software_which_is
copyrighted_by_the_Free_Software_Foundation,_write_to_the_Free
Software_Foundation;_we_sometimes_make_exceptions_for_this.__Our
decision_will_be_guided_by_the_two_goals_of_preserving_the_free_status
of_all_derivatives_of_our_free_software_and_of_promoting_the_sharing
and_reuse_of_software_generally.

____________________________NO_WARRANTY

__15._BECAUSE_THE_LIBRARY_IS_LICENSED_FREE_OF_CHARGE,_THERE_IS_NO
WARRANTY_FOR_THE_LIBRARY,_TO_THE_EXTENT_PERMITTED_BY_APPLICABLE_LAW.
EXCEPT_WHEN_OTHERWISE_STATED_IN_WRITING_THE_COPYRIGHT_HOLDERS_AND/OR
OTHER_PARTIES_PROVIDE_THE_LIBRARY_"AS_IS"_WITHOUT_WARRANTY_OF_ANY
KIND,_EITHER_EXPRESSED_OR_IMPLIED,_INCLUDING,_BUT_NOT_LIMITED_TO,_THE
IMPLIED_WARRANTIES_OF_MERCHANTABILITY_AND_FITNESS_FOR_A_PARTICULAR
PURPOSE.__THE_ENTIRE_RISK_AS_TO_THE_QUALITY_AND_PERFORMANCE_OF_THE
LIBRARY_IS_WITH_YOU.__SHOULD_THE_LIBRARY_PROVE_DEFECTIVE,_YOU_ASSUME
THE_COST_OF_ALL_NECESSARY_SERVICING,_REPAIR_OR_CORRECTION.

__16._IN_NO_EVENT_UNLESS_REQUIRED_BY_APPLICABLE_LAW_OR_AGREED_TO_IN
WRITING_WILL_ANY_COPYRIGHT_HOLDER,_OR_ANY_OTHER_PARTY_WHO_MAY_MODIFY
AND/OR_REDISTRIBUTE_THE_LIBRARY_AS_PERMITTED_ABOVE,_BE_LIABLE_TO_YOU
FOR_DAMAGES,_INCLUDING_ANY_GENERAL,_SPECIAL,_INCIDENTAL_OR
CONSEQUENTIAL_DAMAGES_ARISING_OUT_OF_THE_USE_OR_INABILITY_TO_USE_THE
LIBRARY_(INCLUDING_BUT_NOT_LIMITED_TO_LOSS_OF_DATA_OR_DATA_BEING
RENDERED_INACCURATE_OR_LOSSES_SUSTAINED_BY_YOU_OR_THIRD_PARTIES_OR_A
FAILURE_OF_THE_LIBRARY_TO_OPERATE_WITH_ANY_OTHER_SOFTWARE),_EVEN_IF
SUCH_HOLDER_OR_OTHER_PARTY_HAS_BEEN_ADVISED_OF_THE_POSSIBILITY_OF_SUCH
DAMAGES.

_____________________END_OF_TERMS_AND_CONDITIONS

___________How_to_Apply_These_Terms_to_Your_New_Libraries

__If_you_develop_a_new_library,_and_you_want_it_to_be_of_the_greatest
possible_use_to_the_public,_we_recommend_making_it_free_software_that
everyone_can_redistribute_and_change.__You_can_do_so_by_permitting
redistribution_under_these_terms_(or,_alternatively,_under_the_terms_of_the
ordinary_General_Public_License).

__To_apply_these_terms,_attach_the_following_notices_to_the_library.__It_is
safest_to_attach_them_to_the_start_of_each_source_file_to_most_effectively
convey_the_exclusion_of_warranty;_and_each_file_should_have_at_least_the
"copyright"_line_and_a_pointer_to_where_the_full_notice_is_found.

____<one_line_to_give_the_library's_name_and_a_brief_idea_of_what_it_does.>
____Copyright_(C)_<year>__<name_of_author>

____This_library_is_free_software;_you_can_redistribute_it_and/or
____modify_it_under_the_terms_of_the_GNU_Lesser_General_Public
____License_as_published_by_the_Free_Software_Foundation;_either
____version_2.1_of_the_License,_or_(at_your_option)_any_later_version.

____This_library_is_distributed_in_the_hope_that_it_will_be_useful,
____but_WITHOUT_ANY_WARRANTY;_without_even_the_implied_warranty_of
____MERCHANTABILITY_or_FITNESS_FOR_A_PARTICULAR_PURPOSE.__See_the_GNU
____Lesser_General_Public_License_for_more_details.

____You_should_have_received_a_copy_of_the_GNU_Lesser_General_Public
____License_along_with_this_library;_if_not,_write_to_the_Free_Software
____Foundation,_Inc.,_51_Franklin_Street,_Fifth_Floor,_Boston,_MA__02110-1301
____USA

Also_add_information_on_how_to_contact_you_by_electronic_and_paper_mail.

You_should_also_get_your_employer_(if_you_work_as_a_programmer)_or_your
school,_if_any,_to_sign_a_"copyright_disclaimer"_for_the_library,_if
necessary.__Here_is_a_sample;_alter_the_names:

__Yoyodyne,_Inc.,_hereby_disclaims_all_copyright_interest_in_the
__library_\`Frob'_(a_library_for_tweaking_knobs)_written_by_James_Random
__Hacker.

__<signature_of_Ty_Coon>,_1_April_1990
__Ty_Coon,_President_of_Vice

That's_all_there_is_to_it!
`.replaceAll("_", " "),
  licenseText: {
    "proj853": `
Attribution-ShareAlike_4.0_International

=======================================================================

Creative_Commons_Corporation_("Creative_Commons")_is_not_a_law_firm_and
does_not_provide_legal_services_or_legal_advice._Distribution_of
Creative_Commons_public_licenses_does_not_create_a_lawyer-client_or
other_relationship._Creative_Commons_makes_its_licenses_and_related
information_available_on_an_"as-is"_basis._Creative_Commons_gives_no
warranties_regarding_its_licenses,_any_material_licensed_under_their
terms_and_conditions,_or_any_related_information._Creative_Commons
disclaims_all_liability_for_damages_resulting_from_their_use_to_the
fullest_extent_possible.

Using_Creative_Commons_Public_Licenses

Creative_Commons_public_licenses_provide_a_standard_set_of_terms_and
conditions_that_creators_and_other_rights_holders_may_use_to_share
original_works_of_authorship_and_other_material_subject_to_copyright
and_certain_other_rights_specified_in_the_public_license_below._The
following_considerations_are_for_informational_purposes_only,_are_not
exhaustive,_and_do_not_form_part_of_our_licenses.

_____Considerations_for_licensors:_Our_public_licenses_are
_____intended_for_use_by_those_authorized_to_give_the_public
_____permission_to_use_material_in_ways_otherwise_restricted_by
_____copyright_and_certain_other_rights._Our_licenses_are
_____irrevocable._Licensors_should_read_and_understand_the_terms
_____and_conditions_of_the_license_they_choose_before_applying_it.
_____Licensors_should_also_secure_all_rights_necessary_before
_____applying_our_licenses_so_that_the_public_can_reuse_the
_____material_as_expected._Licensors_should_clearly_mark_any
_____material_not_subject_to_the_license._This_includes_other_CC-
_____licensed_material,_or_material_used_under_an_exception_or
_____limitation_to_copyright._More_considerations_for_licensors:
wiki.creativecommons.org/Considerations_for_licensors

_____Considerations_for_the_public:_By_using_one_of_our_public
_____licenses,_a_licensor_grants_the_public_permission_to_use_the
_____licensed_material_under_specified_terms_and_conditions._If
_____the_licensor's_permission_is_not_necessary_for_any_reason--for
_____example,_because_of_any_applicable_exception_or_limitation_to
_____copyright--then_that_use_is_not_regulated_by_the_license._Our
_____licenses_grant_only_permissions_under_copyright_and_certain
_____other_rights_that_a_licensor_has_authority_to_grant._Use_of
_____the_licensed_material_may_still_be_restricted_for_other
_____reasons,_including_because_others_have_copyright_or_other
_____rights_in_the_material._A_licensor_may_make_special_requests,
_____such_as_asking_that_all_changes_be_marked_or_described.
_____Although_not_required_by_our_licenses,_you_are_encouraged_to
_____respect_those_requests_where_reasonable._More_considerations
_____for_the_public:
wiki.creativecommons.org/Considerations_for_licensees

=======================================================================

Creative_Commons_Attribution-ShareAlike_4.0_International_Public
License

By_exercising_the_Licensed_Rights_(defined_below),_You_accept_and_agree
to_be_bound_by_the_terms_and_conditions_of_this_Creative_Commons
Attribution-ShareAlike_4.0_International_Public_License_("Public
License")._To_the_extent_this_Public_License_may_be_interpreted_as_a
contract,_You_are_granted_the_Licensed_Rights_in_consideration_of_Your
acceptance_of_these_terms_and_conditions,_and_the_Licensor_grants_You
such_rights_in_consideration_of_benefits_the_Licensor_receives_from
making_the_Licensed_Material_available_under_these_terms_and
conditions.


Section_1_--_Definitions.

__a._Adapted_Material_means_material_subject_to_Copyright_and_Similar
_____Rights_that_is_derived_from_or_based_upon_the_Licensed_Material
_____and_in_which_the_Licensed_Material_is_translated,_altered,
_____arranged,_transformed,_or_otherwise_modified_in_a_manner_requiring
_____permission_under_the_Copyright_and_Similar_Rights_held_by_the
_____Licensor._For_purposes_of_this_Public_License,_where_the_Licensed
_____Material_is_a_musical_work,_performance,_or_sound_recording,
_____Adapted_Material_is_always_produced_where_the_Licensed_Material_is
_____synched_in_timed_relation_with_a_moving_image.

__b._Adapter's_License_means_the_license_You_apply_to_Your_Copyright
_____and_Similar_Rights_in_Your_contributions_to_Adapted_Material_in
_____accordance_with_the_terms_and_conditions_of_this_Public_License.

__c._BY-SA_Compatible_License_means_a_license_listed_at
_____creativecommons.org/compatiblelicenses,_approved_by_Creative
_____Commons_as_essentially_the_equivalent_of_this_Public_License.

__d._Copyright_and_Similar_Rights_means_copyright_and/or_similar_rights
_____closely_related_to_copyright_including,_without_limitation,
_____performance,_broadcast,_sound_recording,_and_Sui_Generis_Database
_____Rights,_without_regard_to_how_the_rights_are_labeled_or
_____categorized._For_purposes_of_this_Public_License,_the_rights
_____specified_in_Section_2(b)(1)-(2)_are_not_Copyright_and_Similar
_____Rights.

__e._Effective_Technological_Measures_means_those_measures_that,_in_the
_____absence_of_proper_authority,_may_not_be_circumvented_under_laws
_____fulfilling_obligations_under_Article_11_of_the_WIPO_Copyright
_____Treaty_adopted_on_December_20,_1996,_and/or_similar_international
_____agreements.

__f._Exceptions_and_Limitations_means_fair_use,_fair_dealing,_and/or
_____any_other_exception_or_limitation_to_Copyright_and_Similar_Rights
_____that_applies_to_Your_use_of_the_Licensed_Material.

__g._License_Elements_means_the_license_attributes_listed_in_the_name
_____of_a_Creative_Commons_Public_License._The_License_Elements_of_this
_____Public_License_are_Attribution_and_ShareAlike.

__h._Licensed_Material_means_the_artistic_or_literary_work,_database,
_____or_other_material_to_which_the_Licensor_applied_this_Public
_____License.

__i._Licensed_Rights_means_the_rights_granted_to_You_subject_to_the
_____terms_and_conditions_of_this_Public_License,_which_are_limited_to
_____all_Copyright_and_Similar_Rights_that_apply_to_Your_use_of_the
_____Licensed_Material_and_that_the_Licensor_has_authority_to_license.

__j._Licensor_means_the_individual(s)_or_entity(ies)_granting_rights
_____under_this_Public_License.

__k._Share_means_to_provide_material_to_the_public_by_any_means_or
_____process_that_requires_permission_under_the_Licensed_Rights,_such
_____as_reproduction,_public_display,_public_performance,_distribution,
_____dissemination,_communication,_or_importation,_and_to_make_material
_____available_to_the_public_including_in_ways_that_members_of_the
_____public_may_access_the_material_from_a_place_and_at_a_time
_____individually_chosen_by_them.

__l._Sui_Generis_Database_Rights_means_rights_other_than_copyright
_____resulting_from_Directive_96/9/EC_of_the_European_Parliament_and_of
_____the_Council_of_11_March_1996_on_the_legal_protection_of_databases,
_____as_amended_and/or_succeeded,_as_well_as_other_essentially
_____equivalent_rights_anywhere_in_the_world.

__m._You_means_the_individual_or_entity_exercising_the_Licensed_Rights
_____under_this_Public_License._Your_has_a_corresponding_meaning.


Section_2_--_Scope.

__a._License_grant.

_______1._Subject_to_the_terms_and_conditions_of_this_Public_License,
__________the_Licensor_hereby_grants_You_a_worldwide,_royalty-free,
__________non-sublicensable,_non-exclusive,_irrevocable_license_to
__________exercise_the_Licensed_Rights_in_the_Licensed_Material_to:

____________a._reproduce_and_Share_the_Licensed_Material,_in_whole_or
_______________in_part;_and

____________b._produce,_reproduce,_and_Share_Adapted_Material.

_______2._Exceptions_and_Limitations._For_the_avoidance_of_doubt,_where
__________Exceptions_and_Limitations_apply_to_Your_use,_this_Public
__________License_does_not_apply,_and_You_do_not_need_to_comply_with
__________its_terms_and_conditions.

_______3._Term._The_term_of_this_Public_License_is_specified_in_Section
__________6(a).

_______4._Media_and_formats;_technical_modifications_allowed._The
__________Licensor_authorizes_You_to_exercise_the_Licensed_Rights_in
__________all_media_and_formats_whether_now_known_or_hereafter_created,
__________and_to_make_technical_modifications_necessary_to_do_so._The
__________Licensor_waives_and/or_agrees_not_to_assert_any_right_or
__________authority_to_forbid_You_from_making_technical_modifications
__________necessary_to_exercise_the_Licensed_Rights,_including
__________technical_modifications_necessary_to_circumvent_Effective
__________Technological_Measures._For_purposes_of_this_Public_License,
__________simply_making_modifications_authorized_by_this_Section_2(a)
__________(4)_never_produces_Adapted_Material.

_______5._Downstream_recipients.

____________a._Offer_from_the_Licensor_--_Licensed_Material._Every
_______________recipient_of_the_Licensed_Material_automatically
_______________receives_an_offer_from_the_Licensor_to_exercise_the
_______________Licensed_Rights_under_the_terms_and_conditions_of_this
_______________Public_License.

____________b._Additional_offer_from_the_Licensor_--_Adapted_Material.
_______________Every_recipient_of_Adapted_Material_from_You
_______________automatically_receives_an_offer_from_the_Licensor_to
_______________exercise_the_Licensed_Rights_in_the_Adapted_Material
_______________under_the_conditions_of_the_Adapter's_License_You_apply.

____________c._No_downstream_restrictions._You_may_not_offer_or_impose
_______________any_additional_or_different_terms_or_conditions_on,_or
_______________apply_any_Effective_Technological_Measures_to,_the
_______________Licensed_Material_if_doing_so_restricts_exercise_of_the
_______________Licensed_Rights_by_any_recipient_of_the_Licensed
_______________Material.

_______6._No_endorsement._Nothing_in_this_Public_License_constitutes_or
__________may_be_construed_as_permission_to_assert_or_imply_that_You
__________are,_or_that_Your_use_of_the_Licensed_Material_is,_connected
__________with,_or_sponsored,_endorsed,_or_granted_official_status_by,
__________the_Licensor_or_others_designated_to_receive_attribution_as
__________provided_in_Section_3(a)(1)(A)(i).

__b._Other_rights.

_______1._Moral_rights,_such_as_the_right_of_integrity,_are_not
__________licensed_under_this_Public_License,_nor_are_publicity,
__________privacy,_and/or_other_similar_personality_rights;_however,_to
__________the_extent_possible,_the_Licensor_waives_and/or_agrees_not_to
__________assert_any_such_rights_held_by_the_Licensor_to_the_limited
__________extent_necessary_to_allow_You_to_exercise_the_Licensed
__________Rights,_but_not_otherwise.

_______2._Patent_and_trademark_rights_are_not_licensed_under_this
__________Public_License.

_______3._To_the_extent_possible,_the_Licensor_waives_any_right_to
__________collect_royalties_from_You_for_the_exercise_of_the_Licensed
__________Rights,_whether_directly_or_through_a_collecting_society
__________under_any_voluntary_or_waivable_statutory_or_compulsory
__________licensing_scheme._In_all_other_cases_the_Licensor_expressly
__________reserves_any_right_to_collect_such_royalties.


Section_3_--_License_Conditions.

Your_exercise_of_the_Licensed_Rights_is_expressly_made_subject_to_the
following_conditions.

__a._Attribution.

_______1._If_You_Share_the_Licensed_Material_(including_in_modified
__________form),_You_must:

____________a._retain_the_following_if_it_is_supplied_by_the_Licensor
_______________with_the_Licensed_Material:

_________________i._identification_of_the_creator(s)_of_the_Licensed
____________________Material_and_any_others_designated_to_receive
____________________attribution,_in_any_reasonable_manner_requested_by
____________________the_Licensor_(including_by_pseudonym_if
____________________designated);

________________ii._a_copyright_notice;

_______________iii._a_notice_that_refers_to_this_Public_License;

________________iv._a_notice_that_refers_to_the_disclaimer_of
____________________warranties;

_________________v._a_URI_or_hyperlink_to_the_Licensed_Material_to_the
____________________extent_reasonably_practicable;

____________b._indicate_if_You_modified_the_Licensed_Material_and
_______________retain_an_indication_of_any_previous_modifications;_and

____________c._indicate_the_Licensed_Material_is_licensed_under_this
_______________Public_License,_and_include_the_text_of,_or_the_URI_or
_______________hyperlink_to,_this_Public_License.

_______2._You_may_satisfy_the_conditions_in_Section_3(a)(1)_in_any
__________reasonable_manner_based_on_the_medium,_means,_and_context_in
__________which_You_Share_the_Licensed_Material._For_example,_it_may_be
__________reasonable_to_satisfy_the_conditions_by_providing_a_URI_or
__________hyperlink_to_a_resource_that_includes_the_required
__________information.

_______3._If_requested_by_the_Licensor,_You_must_remove_any_of_the
__________information_required_by_Section_3(a)(1)(A)_to_the_extent
__________reasonably_practicable.

__b._ShareAlike.

_____In_addition_to_the_conditions_in_Section_3(a),_if_You_Share
_____Adapted_Material_You_produce,_the_following_conditions_also_apply.

_______1._The_Adapter's_License_You_apply_must_be_a_Creative_Commons
__________license_with_the_same_License_Elements,_this_version_or
__________later,_or_a_BY-SA_Compatible_License.

_______2._You_must_include_the_text_of,_or_the_URI_or_hyperlink_to,_the
__________Adapter's_License_You_apply._You_may_satisfy_this_condition
__________in_any_reasonable_manner_based_on_the_medium,_means,_and
__________context_in_which_You_Share_Adapted_Material.

_______3._You_may_not_offer_or_impose_any_additional_or_different_terms
__________or_conditions_on,_or_apply_any_Effective_Technological
__________Measures_to,_Adapted_Material_that_restrict_exercise_of_the
__________rights_granted_under_the_Adapter's_License_You_apply.


Section_4_--_Sui_Generis_Database_Rights.

Where_the_Licensed_Rights_include_Sui_Generis_Database_Rights_that
apply_to_Your_use_of_the_Licensed_Material:

__a._for_the_avoidance_of_doubt,_Section_2(a)(1)_grants_You_the_right
_____to_extract,_reuse,_reproduce,_and_Share_all_or_a_substantial
_____portion_of_the_contents_of_the_database;

__b._if_You_include_all_or_a_substantial_portion_of_the_database
_____contents_in_a_database_in_which_You_have_Sui_Generis_Database
_____Rights,_then_the_database_in_which_You_have_Sui_Generis_Database
_____Rights_(but_not_its_individual_contents)_is_Adapted_Material,

_____including_for_purposes_of_Section_3(b);_and
__c._You_must_comply_with_the_conditions_in_Section_3(a)_if_You_Share
_____all_or_a_substantial_portion_of_the_contents_of_the_database.

For_the_avoidance_of_doubt,_this_Section_4_supplements_and_does_not
replace_Your_obligations_under_this_Public_License_where_the_Licensed
Rights_include_other_Copyright_and_Similar_Rights.


Section_5_--_Disclaimer_of_Warranties_and_Limitation_of_Liability.

__a._UNLESS_OTHERWISE_SEPARATELY_UNDERTAKEN_BY_THE_LICENSOR,_TO_THE
_____EXTENT_POSSIBLE,_THE_LICENSOR_OFFERS_THE_LICENSED_MATERIAL_AS-IS
_____AND_AS-AVAILABLE,_AND_MAKES_NO_REPRESENTATIONS_OR_WARRANTIES_OF
_____ANY_KIND_CONCERNING_THE_LICENSED_MATERIAL,_WHETHER_EXPRESS,
_____IMPLIED,_STATUTORY,_OR_OTHER._THIS_INCLUDES,_WITHOUT_LIMITATION,
_____WARRANTIES_OF_TITLE,_MERCHANTABILITY,_FITNESS_FOR_A_PARTICULAR
_____PURPOSE,_NON-INFRINGEMENT,_ABSENCE_OF_LATENT_OR_OTHER_DEFECTS,
_____ACCURACY,_OR_THE_PRESENCE_OR_ABSENCE_OF_ERRORS,_WHETHER_OR_NOT
_____KNOWN_OR_DISCOVERABLE._WHERE_DISCLAIMERS_OF_WARRANTIES_ARE_NOT
_____ALLOWED_IN_FULL_OR_IN_PART,_THIS_DISCLAIMER_MAY_NOT_APPLY_TO_YOU.

__b._TO_THE_EXTENT_POSSIBLE,_IN_NO_EVENT_WILL_THE_LICENSOR_BE_LIABLE
_____TO_YOU_ON_ANY_LEGAL_THEORY_(INCLUDING,_WITHOUT_LIMITATION,
_____NEGLIGENCE)_OR_OTHERWISE_FOR_ANY_DIRECT,_SPECIAL,_INDIRECT,
_____INCIDENTAL,_CONSEQUENTIAL,_PUNITIVE,_EXEMPLARY,_OR_OTHER_LOSSES,
_____COSTS,_EXPENSES,_OR_DAMAGES_ARISING_OUT_OF_THIS_PUBLIC_LICENSE_OR
_____USE_OF_THE_LICENSED_MATERIAL,_EVEN_IF_THE_LICENSOR_HAS_BEEN
_____ADVISED_OF_THE_POSSIBILITY_OF_SUCH_LOSSES,_COSTS,_EXPENSES,_OR
_____DAMAGES._WHERE_A_LIMITATION_OF_LIABILITY_IS_NOT_ALLOWED_IN_FULL_OR
_____IN_PART,_THIS_LIMITATION_MAY_NOT_APPLY_TO_YOU.

__c._The_disclaimer_of_warranties_and_limitation_of_liability_provided
_____above_shall_be_interpreted_in_a_manner_that,_to_the_extent
_____possible,_most_closely_approximates_an_absolute_disclaimer_and
_____waiver_of_all_liability.


Section_6_--_Term_and_Termination.

__a._This_Public_License_applies_for_the_term_of_the_Copyright_and
_____Similar_Rights_licensed_here._However,_if_You_fail_to_comply_with
_____this_Public_License,_then_Your_rights_under_this_Public_License
_____terminate_automatically.

__b._Where_Your_right_to_use_the_Licensed_Material_has_terminated_under
_____Section_6(a),_it_reinstates:

_______1._automatically_as_of_the_date_the_violation_is_cured,_provided
__________it_is_cured_within_30_days_of_Your_discovery_of_the
__________violation;_or

_______2._upon_express_reinstatement_by_the_Licensor.

_____For_the_avoidance_of_doubt,_this_Section_6(b)_does_not_affect_any
_____right_the_Licensor_may_have_to_seek_remedies_for_Your_violations
_____of_this_Public_License.

__c._For_the_avoidance_of_doubt,_the_Licensor_may_also_offer_the
_____Licensed_Material_under_separate_terms_or_conditions_or_stop
_____distributing_the_Licensed_Material_at_any_time;_however,_doing_so
_____will_not_terminate_this_Public_License.

__d._Sections_1,_5,_6,_7,_and_8_survive_termination_of_this_Public
_____License.


Section_7_--_Other_Terms_and_Conditions.

__a._The_Licensor_shall_not_be_bound_by_any_additional_or_different
_____terms_or_conditions_communicated_by_You_unless_expressly_agreed.

__b._Any_arrangements,_understandings,_or_agreements_regarding_the
_____Licensed_Material_not_stated_herein_are_separate_from_and
_____independent_of_the_terms_and_conditions_of_this_Public_License.


Section_8_--_Interpretation.

__a._For_the_avoidance_of_doubt,_this_Public_License_does_not,_and
_____shall_not_be_interpreted_to,_reduce,_limit,_restrict,_or_impose
_____conditions_on_any_use_of_the_Licensed_Material_that_could_lawfully
_____be_made_without_permission_under_this_Public_License.

__b._To_the_extent_possible,_if_any_provision_of_this_Public_License_is
_____deemed_unenforceable,_it_shall_be_automatically_reformed_to_the
_____minimum_extent_necessary_to_make_it_enforceable._If_the_provision
_____cannot_be_reformed,_it_shall_be_severed_from_this_Public_License
_____without_affecting_the_enforceability_of_the_remaining_terms_and
_____conditions.

__c._No_term_or_condition_of_this_Public_License_will_be_waived_and_no
_____failure_to_comply_consented_to_unless_expressly_agreed_to_by_the
_____Licensor.

__d._Nothing_in_this_Public_License_constitutes_or_may_be_interpreted
_____as_a_limitation_upon,_or_waiver_of,_any_privileges_and_immunities
_____that_apply_to_the_Licensor_or_You,_including_from_the_legal
_____processes_of_any_jurisdiction_or_authority.


=======================================================================

Creative_Commons_is_not_a_party_to_its_public
licenses._Notwithstanding,_Creative_Commons_may_elect_to_apply_one_of
its_public_licenses_to_material_it_publishes_and_in_those_instances
will_be_considered_the_“Licensor.”_The_text_of_the_Creative_Commons
public_licenses_is_dedicated_to_the_public_domain_under_the_CC0_Public
Domain_Dedication._Except_for_the_limited_purpose_of_indicating_that
material_is_shared_under_a_Creative_Commons_public_license_or_as
otherwise_permitted_by_the_Creative_Commons_policies_published_at
creativecommons.org/policies,_Creative_Commons_does_not_authorize_the
use_of_the_trademark_"Creative_Commons"_or_any_other_trademark_or_logo
of_Creative_Commons_without_its_prior_written_consent_including,
without_limitation,_in_connection_with_any_unauthorized_modifications
to_any_of_its_public_licenses_or_any_other_arrangements,
understandings,_or_agreements_concerning_use_of_licensed_material._For
the_avoidance_of_doubt,_this_paragraph_does_not_form_part_of_the
public_licenses.

Creative_Commons_may_be_contacted_at_creativecommons.org.
`.replaceAll("_", " "),
    "js-base64": `
Copyright (c) 2014, Dan Kogai All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

Neither the name of {{{project}}} nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
`,
    "semver": `
The ISC License

Copyright (c) Isaac Z. Schlueter and Contributors

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
`,
    "tdesign-miniprogram": `
MIT License

Copyright (c) 2021-present TDesign

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
`,
  }
};